# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Common configuration for jobs :
#executors:
#  my-executor:
#    docker:
#      - image: buildpack-deps:jessie
#        auth:
#          username: mydockerhub-user
#          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#    working_directory: /tmp

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:

  clone-repository:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: small
    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: Building common
          command: mvn clean install -f backend/cloud-stream-common/pom.xml
      - run:
          name: Building repository
          command: mvn clean install -f backend/cloud-stream-repository/pom.xml
      - run:
          name: Building domain
          command: mvn clean install -f backend/cloud-stream-domain/pom.xml
      - persist_to_workspace:
          root: workspace
          paths:
            - backend
            - frontend

  microservice-build-deploy:
    parameters:
      microservice-module-name:
        type: string
    docker:
      - image: cimg/openjdk:17.0
    resource_class: small
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Listing ./
          command: ls -l ./
      - run:
          name: Listing /tmp
          command: ls -l /tmp
#      - run:
#          name: Listing the repository (backend)
#          command: ls -l ./backend
#      - run:
#          name: Listing the repository (frontend)
#          command: ls -l ./frontend
#      - run:
#          name: Building << parameters.microservice-module-name >>
#          command: mvn clean install -f ./backend/<< parameters.microservice-module-name >>/pom.xml

workflows:

  common:
    jobs:
      - clone-repository:
          filters:
            branches:
              only: master
  backend:
    jobs:
      - microservice-build-deploy:
          microservice-module-name: cloud-stream-api-user
          filters:
            branches:
              only: master
      - microservice-build-deploy:
          microservice-module-name: cloud-stream-api-storage
          filters:
            branches:
              only: master
      - microservice-build-deploy:
          microservice-module-name: cloud-stream-api-stream
          filters:
            branches:
              only: master
      - microservice-build-deploy:
          microservice-module-name: cloud-stream-api-download
          filters:
            branches:
              only: master