version: 2.1

executors:
  cloud-stream-executor:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: medium
    working_directory: ~/project

jobs:
  clone-repository:
    executor: cloud-stream-executor
    steps:
      - checkout
      - run:
          name: Building common
          command: mvn clean install -f backend/cloud-stream-common/pom.xml
      - run:
          name: Building repository
          command: mvn clean install -f backend/cloud-stream-repository/pom.xml
      - run:
          name: Building domain
          command: mvn clean install -f backend/cloud-stream-domain/pom.xml
      - persist_to_workspace:
          root: .
          paths:
            - backend
            - frontend
  microservice-build:
    executor: cloud-stream-executor
    parameters:
      microservice-module-name:
        type: string
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Building << parameters.microservice-module-name >>
          command: mvn clean package -f backend/<< parameters.microservice-module-name >>/pom.xml

workflows:
  integration:
    jobs:
      - clone-repository:
          filters:
            branches:
              only: master
      - microservice-build:
          requires:
            - clone-repository
          microservice-module-name: cloud-stream-api-user
          filters:
            branches:
              only: master
      - microservice-build:
          requires:
            - clone-repository
          microservice-module-name: cloud-stream-api-storage
          filters:
            branches:
              only: master
      - microservice-build:
          requires:
            - clone-repository
          microservice-module-name: cloud-stream-api-stream
          filters:
            branches:
              only: master
      - microservice-build:
          requires:
            - clone-repository
          microservice-module-name: cloud-stream-api-download
          filters:
            branches:
              only: master
#    deployment: TODO