# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:

  clone-repository:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Building common
          command: mvn clean install -f backend/cloud-stream-common/pom.xml
      - run:
          name: Building repository
          command: mvn clean install -f backend/cloud-stream-repository/pom.xml
      - run:
          name: Building domain
          command: mvn clean install -f backend/cloud-stream-domain/pom.xml
      - run:
          name: Listing the respository content
          command: ls -l /home/circleci/project
      - run:
          name: Listing the working directory before saving
          command: ls -l /tmp/workspace
      - persist_to_workspace:
          root: .
          paths:
            - backend
            - frontend
      - run:
          name: Listing the working directory after saving
          command: ls -l /tmp/workspace

  microservice-build-deploy:
    parameters:
      microservice-module-name:
        type: string
    docker:
      - image: cimg/openjdk:17.0
    resource_class: small
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Listing the attached workspace content
          command: ls -l ./
      - run:
          name: Listing the original workspace content
          command: ls -l /tmp/workspace
#      - run:
#          name: Listing the repository (backend)
#          command: ls -l ./backend
#      - run:
#          name: Listing the repository (frontend)
#          command: ls -l ./frontend
#      - run:
#          name: Building << parameters.microservice-module-name >>
#          command: mvn clean install -f ./backend/<< parameters.microservice-module-name >>/pom.xml

workflows:

  common:
    jobs:
      - clone-repository:
          filters:
            branches:
              only: master
  backend:
    jobs:
      - microservice-build-deploy:
          microservice-module-name: cloud-stream-api-user
          filters:
            branches:
              only: master
      - microservice-build-deploy:
          microservice-module-name: cloud-stream-api-storage
          filters:
            branches:
              only: master
      - microservice-build-deploy:
          microservice-module-name: cloud-stream-api-stream
          filters:
            branches:
              only: master
      - microservice-build-deploy:
          microservice-module-name: cloud-stream-api-download
          filters:
            branches:
              only: master