version: 2.1

executors:
  cloud-stream-executor:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: medium
    working_directory: ~/project

jobs:
  clone-repository:
    executor: cloud-stream-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "backend/pom.xml" }}
      - run:
          name: Building common
          command: mvn install -f backend/cloud-stream-common/pom.xml
      - run:
          name: Building repository
          command: mvn install -f backend/cloud-stream-repository/pom.xml
      - run:
          name: Building domain
          command: mvn install -f backend/cloud-stream-domain/pom.xml
      - persist_to_workspace:
          root: .
          paths:
            - backend
            - frontend
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "backend/pom.xml" }}

  microservice-build:
    executor: cloud-stream-executor
    parameters:
      microservice-module-name:
        type: string
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "backend/pom.xml" }}
      - run:
          name: Resolving Maven dependencies
          command: mvn dependency:resolve -f backend/pom.xml
      - run:
          name: Building << parameters.microservice-module-name >>
          command: mvn package -f backend/<< parameters.microservice-module-name >>/pom.xml -X
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "backend/pom.xml" }}

workflows:
  integration:
    jobs:
      - clone-repository:
          filters:
            branches:
              only: master
      - microservice-build:
          requires:
            - clone-repository
          microservice-module-name: cloud-stream-api-user
          filters:
            branches:
              only: master
      - microservice-build:
          requires:
            - clone-repository
          microservice-module-name: cloud-stream-api-storage
          filters:
            branches:
              only: master
      - microservice-build:
          requires:
            - clone-repository
          microservice-module-name: cloud-stream-api-stream
          filters:
            branches:
              only: master
      - microservice-build:
          requires:
            - clone-repository
          microservice-module-name: cloud-stream-api-download
          filters:
            branches:
              only: master
#    deployment: TODO