version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

executors:
  cloud-stream-executor:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: medium
    environment:
      JVM_OPTS: -Xmx3g

jobs:
  clone-repository:
    executor: cloud-stream-executor
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - backend
            - frontend

  backend-build-artefacts:
    executor: cloud-stream-executor
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - maven-dependencies-repository-v2-{{ checksum "backend/pom.xml" }}
      - run:
          name: Building backend
          command: mvn install -f backend/pom.xml
      - persist_to_workspace:
          root: .
          paths:
            - backend
            - frontend
      - save_cache:
          paths:
            - /home/circleci/.m2/
          key: maven-dependencies-repository-v2-{{ checksum "backend/pom.xml" }}

  backend-build-container-image:
    executor: cloud-stream-executor
    parameters:
      microservice-module-name:
        type: string
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - maven-dependencies-repository-v2-{{ checksum "backend/pom.xml" }}
      - setup_remote_docker
      - run:
          name: Running << parameters.microservice-module-name >>
          command: mvn spring-boot:build-image -f backend/<< parameters.microservice-module-name >>/pom.xml
      - run:
          name: Docker list images
          command: docker image ls -a
      - run:
          name: Logging to Heroku Docker registry
          command: docker login --username=mottier.aurelien.shopping@gmail.com --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Removing docker latest image from Heroku
          command: docker rmi registry.heroku.com/<< parameters.microservice-module-name >>/web:latest
      - run:
          name: Tagging docker image to Heroku
          command: docker tag aurelienmottier/<< parameters.microservice-module-name >>:v1.0.0 registry.heroku.com/<< parameters.microservice-module-name >>/web:latest
      - run:
          name: Pushing docker image to Heroku
          command: docker push registry.heroku.com/<< parameters.microservice-module-name >>/web:latest
      - heroku/install
      - run:
          name: Heroku login
          command: heroku container:login
      - run:
          name: Heroku release
          command: heroku container:release web -a << parameters.microservice-module-name >>
      - run:
          name: Heroku logout
          command: heroku container:logout

workflows:
  release-pipeline:
    jobs:
      - clone-repository:
          filters:
            branches:
              only: master
      - backend-build-artefacts:
          requires:
            - clone-repository
#      - backend-build-container-image:
#          requires:
#            - backend-build-artefacts
#          microservice-module-name: cloud-stream-api-user
#      - backend-build-container-image:
#          requires:
#            - backend-build-artefacts
#          microservice-module-name: cloud-stream-api-storage
#      - backend-build-container-image:
#          requires:
#            - backend-build-artefacts
#          microservice-module-name: cloud-stream-api-stream
      - backend-build-container-image:
          requires:
            - backend-build-artefacts
          microservice-module-name: cloud-stream-api-download